#ifndef REQUEST_TYPE_H
#define REQUEST_TYPE_H

#define REQUEST_TYPE_SET_INFO 1
#define REQUEST_TYPE_LISTCLIENTS 2
#define REQUEST_TYPE_INFOCLIENT 3
#define REQUEST_TYPE_SHARE 4
#define REQUEST_TYPE_UNSHARE 5
#define REQUEST_TYPE_GETSHARE 6
#define REQUEST_TYPE_DISCONNECT 7
#define REQUEST_TYPE_INFOCLIENT_SILENT 8
#define REQUEST_TYPE_MESSAGE 9
#define REQUEST_TYPE_FILE_WRITE_DATA 10
#define REQUEST_TYPE_EOF 11
#define REQUEST_TYPE_START_TRANSFER 12
#define REQUEST_TYPE_ABORT_UNABLE_TO_OPEN_FILE 13

#endif
