#ifndef RESPONSE_H
#define RESPONSE_H

#define RESPONSE_SUCCESS 0
#define RESPONSE_NAME_EXISTS 1
#define RESPONSE_LISTCLIENTS 3
#define RESPONSE_INEXISTENT_CLIENT 4
#define RESPONSE_CLIENTINFO 5
#define RESPONSE_GETSHARE 6
#define RESPONSE_CLIENTINFO_SILENT 7

#endif